encoding: UTF-8
title: NEO Hackathons
author: NEO Foundation
email: contact@neo.org
description: > # this means to ignore newlines until "twitter_username:"
  We believe that Hackathons and community led competitions can be very helpful 
  for connecting the neo community and developing the neo ecosystem.

# Build settings
theme: jekyll-theme-cayman

plugins:
 - jekyll-feed
 - jekyll-seo-tag
